### ISSUE TITLE
Feature request: Add a material scan benchmark

### ISSUE THREAD

**Issue by veprbl** [eic/detector_benchmarks#16]
We have a very nice https://github.com/eic/epic/blob/main/bin/g4MaterialScan_to_csv by @Chao1009 that gives $X_0$/$\Lambda$ per material. And we see nice material scans shown in the calorimetry meetings by @mariakzurek and @jizhongling. But there is no public code to produce those, as this is a common request. Would be very nice if someone could share a working code that we can add automation for.

**Comment by veprbl** [comment]
And how does it even work? Do we need an epic configuration that replaces all the materials with the detector names?

**Comment by mariakzurek** [comment]
I'm using public code added in this PR https://github.com/eic/epic/pull/381

**Comment by veprbl** [comment]
@mariakzurek That was the one. Thanks!
